---@meta

--- Primary configuration table.
---@class bars.config
---
--- When true, all options are set
--- **globally**.
--- Can be used to prevent visible
--- changes to the bars & lines when
--- opening Neovim or new windows.
---@field global? boolean
---
---@field statusline? boolean | statusline.config Statusline configuration.
---@field statuscolumn? boolean | statuscolumn.config Statuscolumn configuration.
---@field winbar? boolean | winbar.config Winbar configuration.
---
---@field tabline? boolean | tabline.config Tabline configuration.
